repos:
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      - id: php-cs
        name: PHP Codesniffer
        files: \.php$
        args: [--standard=.phpcs.xml --ignore=vendor/ -p --warning-severity=0]
  - repo: local
    hooks:
      - id: php-syntax-check
        name: PHP Syntax Check
        entry: ./syntax_check.sh
        args: [-e, vendor/]
        language: script
        pass_filenames: true
        files: \.php$
        stages: [commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
